import { defineCollection, z } from 'astro:content';
import { file } from 'astro/loaders';
import peopleData from './data/people.json';
import productionsData from './data/productions.json';

// Id sets for cross-reference validation. A typo'd reference in items.json
// fails the build instead of silently rendering a broken page.
const personIds = new Set(peopleData.map((p) => p.id));
const productionIds = new Set(productionsData.map((p) => p.id));

const slugPattern = /^[a-z0-9]+(-[a-z0-9]+)*$/;

const people = defineCollection({
  loader: file('src/data/people.json'),
  schema: z.object({
    id: z.string().regex(slugPattern),
    name: z.string().min(1),
    role: z.string().min(1),
    years: z.string().min(1),
    // Null until a real portrait is cleared for this person. The AI-generated
    // placeholders were removed; an empty frame is honest, an invented face is not.
    thumbnail: z.string().nullable(),
    portrait: z.string().nullable(),
    bio: z.string().min(1),
  }),
});

// The three producing organizations the source list distinguishes between.
export const COMPANIES = {
  'greenwich-mews-theatre': 'Greenwich Mews Theatre',
  'greenwich-mews-spanish-theatre': 'Greenwich Mews Spanish Theatre',
  'village-church-arts-ministry': 'Arts Ministry of the Village Church',
} as const;

const productions = defineCollection({
  loader: file('src/data/productions.json'),
  schema: z.object({
    id: z.string().regex(slugPattern),
    year: z.number().int(),
    title: z.string().min(1),
    company: z.enum(
      Object.keys(COMPANIES) as [keyof typeof COMPANIES, ...(keyof typeof COMPANIES)[]]
    ),
    playwright: z.string().min(1),
    director: z.string().min(1),
    cast: z.array(z.string()),
    // Every remaining credit line from the source list, in printed order —
    // producers, designers, stage management, music, translation, and so on.
    credits: z
      .array(
        z.object({
          role: z.string().min(1),
          names: z.string().min(1),
        })
      )
      .min(1),
    notes: z.string(),
    featured: z.boolean(),
    image: z.string().nullable(),
    description: z.string().nullable(),
  }),
});

const items = defineCollection({
  loader: file('src/data/items.json'),
  schema: z.object({
    id: z.string().regex(slugPattern),
    // The author's own figure number, so an item on the page can be traced
    // back to a row of her permissions spreadsheet.
    figId: z.string().min(1),
    title: z.string().min(1),
    // Null until a scan exists for this row; the page renders an empty frame
    // rather than inventing a picture.
    image: z.string().nullable(),
    caption: z.string().min(1),
    creator: z.string(),
    // date/source/rights are intentionally allowed to be empty. The catalog is
    // still being assembled, and a blank cell is recorded in `needs` below so
    // the gap shows on the page instead of being filled with a plausible guess.
    date: z.string(),
    source: z.string(),
    rights: z.string(),
    // Human-readable list of what this record is still missing, generated by
    // scripts/import-items/build.py. Empty means the row is complete.
    needs: z.array(z.string()),
    tags: z.array(z.string().regex(slugPattern)).min(1),
    people: z.array(
      z.string().refine((id) => personIds.has(id), (id) => ({
        message: `Unknown person id "${id}" — must match an id in people.json`,
      }))
    ),
    // Names that appear in the productions appendix but have no profile of
    // their own. Stored as the name exactly as printed, which is what the
    // contributor index is keyed by.
    contributors: z.array(z.string().min(1)),
    productions: z.array(
      z.string().refine((id) => productionIds.has(id), (id) => ({
        message: `Unknown production id "${id}" — must match an id in productions.json`,
      }))
    ),
  }),
});

export const collections = { people, productions, items };
